function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // Pause_Control
	global.__objectDepths[1] = 0; // obj_Pause_Parent
	global.__objectDepths[2] = -1; // obj_Soul_Menu_Butt
	global.__objectDepths[3] = -1; // obj_Recollection_Menu_Butt
	global.__objectDepths[4] = -1; // obj_Settings_Menu_Butt
	global.__objectDepths[5] = -1; // obj_Save_Quit
	global.__objectDepths[6] = 0; // obj_Pause
	global.__objectDepths[7] = -1; // obj_Pause_Sparkle
	global.__objectDepths[8] = 0; // obj_Settings_Menu
	global.__objectDepths[9] = -2; // obj_Specific_Setting_Butt
	global.__objectDepths[10] = -2; // obj_Option_Button
	global.__objectDepths[11] = -2; // obj_Option_Pointer
	global.__objectDepths[12] = -2; // obj_Option_Slider
	global.__objectDepths[13] = 0; // obj_Soul_Menu
	global.__objectDepths[14] = -1; // obj_Soul_Stat_Meter
	global.__objectDepths[15] = -3; // obj_Soul_Stat_Calc_Icon
	global.__objectDepths[16] = -1; // obj_Item_Butt
	global.__objectDepths[17] = 0; // obj_Recollection_Menu
	global.__objectDepths[18] = -1; // obj_Recollection_Category_Butt
	global.__objectDepths[19] = -1; // obj_Recollection_Butt
	global.__objectDepths[20] = -1; // obj_Recollect_Spark
	global.__objectDepths[21] = -1; // obj_Recollection_Info_Butt
	global.__objectDepths[22] = 0; // Soul_Hearts_Control
	global.__objectDepths[23] = -1000; // obj_Heart_Butt
	global.__objectDepths[24] = 0; // obj_Mouse_Heart
	global.__objectDepths[25] = 0; // Control_Parent
	global.__objectDepths[26] = 0; // Game_Start_Control
	global.__objectDepths[27] = 0; // Chapter_Change_Control
	global.__objectDepths[28] = -100; // Floor_Layout_Control
	global.__objectDepths[29] = 0; // Soul_Weapons_Control
	global.__objectDepths[30] = 0; // Soul_Stat_Control
	global.__objectDepths[31] = -100; // obj_Loading_Screen
	global.__objectDepths[32] = 0; // obj_Depth
	global.__objectDepths[33] = 0; // obj_Depth_Floor
	global.__objectDepths[34] = 0; // Master_Depth_Draw_Control
	global.__objectDepths[35] = 10; // obj_Environmental_Control
	global.__objectDepths[36] = 0; // Music_Control
	global.__objectDepths[37] = -10; // Tutorial_Control
	global.__objectDepths[38] = 0; // Run_Fade_Control
	global.__objectDepths[39] = 0; // Camera_Control
	global.__objectDepths[40] = 0; // Gui_Control
	global.__objectDepths[41] = -2; // obj_Light_Control
	global.__objectDepths[42] = 0; // Boss_Room_Start_Control
	global.__objectDepths[43] = 0; // Normal_Room_Start_Control
	global.__objectDepths[44] = 0; // Item_Room_Control
	global.__objectDepths[45] = 0; // Shop_Room_Control
	global.__objectDepths[46] = 0; // obj_Sparkle_Emitter
	global.__objectDepths[47] = 0; // obj_Heart_Emitter
	global.__objectDepths[48] = 0; // obj_Dream_Emitter
	global.__objectDepths[49] = 0; // obj_Environment_Emitter
	global.__objectDepths[50] = -5; // obj_Damage_Indicator
	global.__objectDepths[51] = 0; // obj_Field_Element
	global.__objectDepths[52] = -50; // obj_Fade
	global.__objectDepths[53] = -2; // obj_Light
	global.__objectDepths[54] = 0; // obj_Border_Impact
	global.__objectDepths[55] = 1; // obj_The_Border
	global.__objectDepths[56] = 1; // obj_Bigger_Border
	global.__objectDepths[57] = 0; // obj_Flash_Sparkle
	global.__objectDepths[58] = 0; // obj_Feel_Heart
	global.__objectDepths[59] = 0; // obj_Dream_Cloud
	global.__objectDepths[60] = 0; // obj_Big_Dream_Cloud
	global.__objectDepths[61] = 1; // obj_Medium_Room_Wall
	global.__objectDepths[62] = -1000000; // obj_Astral_Indicator
	global.__objectDepths[63] = -1000000; // obj_Charge_Indicator
	global.__objectDepths[64] = -1000000; // obj_Dream_Cursor
	global.__objectDepths[65] = 0; // obj_Soul
	global.__objectDepths[66] = 0; // obj_Soul_Parent
	global.__objectDepths[67] = 0; // obj_Soul_Flash
	global.__objectDepths[68] = 0; // obj_Soul_Spiritual
	global.__objectDepths[69] = 0; // obj_Soul_Feel
	global.__objectDepths[70] = 0; // obj_Soul_Dream
	global.__objectDepths[71] = 0; // obj_Soul_Bit
	global.__objectDepths[72] = -1; // obj_Broken_Heart
	global.__objectDepths[73] = -1; // obj_Soul_Linger
	global.__objectDepths[74] = 0; // obj_Dream_Glitch
	global.__objectDepths[75] = 0; // obj_Soul_Nightmare
	global.__objectDepths[76] = -1; // obj_Basic_Soul
	global.__objectDepths[77] = 0; // obj_Projectile_Parent
	global.__objectDepths[78] = 0; // obj_Basic_Projectile_Parent
	global.__objectDepths[79] = -1; // obj_Lesser_Soul_Shot
	global.__objectDepths[80] = -1; // obj_Defense_Soul_Shot
	global.__objectDepths[81] = 0; // obj_Essence_Impact_Show
	global.__objectDepths[82] = 0; // obj_Direction_Soul_Shot
	global.__objectDepths[83] = 0; // obj_Minion_Parent
	global.__objectDepths[84] = 0; // obj_Minion_Phase
	global.__objectDepths[85] = 0; // obj_Spooked_Ghoul
	global.__objectDepths[86] = 0; // obj_Wall_Fiend
	global.__objectDepths[87] = 0; // obj_Re_Animated
	global.__objectDepths[88] = 0; // obj_Mini_Manifest
	global.__objectDepths[89] = 0; // obj_Unrest_Spirit
	global.__objectDepths[90] = 0; // obj_Wrath_Spirit
	global.__objectDepths[91] = 0; // obj_Demon_Unrest
	global.__objectDepths[92] = 0; // obj_Distorted_Ghoul
	global.__objectDepths[93] = 0; // obj_Hope_Mask
	global.__objectDepths[94] = 0; // obj_Jello_Minion
	global.__objectDepths[95] = 0; // obj_Jumpy_Slime
	global.__objectDepths[96] = 0; // obj_Scary_Heart
	global.__objectDepths[97] = 0; // obj_Hand_Slime
	global.__objectDepths[98] = 0; // obj_Toxic_Slime
	global.__objectDepths[99] = 0; // obj_Spike_Slime
	global.__objectDepths[100] = 0; // obj_Poison_Jello
	global.__objectDepths[101] = 0; // obj_Jello_Cube
	global.__objectDepths[102] = 0; // obj_Poison_Cube
	global.__objectDepths[103] = 0; // obj_Boss_Parent
	global.__objectDepths[104] = 0; // obj_Main_Boss_Parent
	global.__objectDepths[105] = 0; // obj_Non_Solid_Boss_Parent
	global.__objectDepths[106] = 0; // obj_Wall_Stop_Boss_Parent
	global.__objectDepths[107] = -1; // obj_Boost_Spark
	global.__objectDepths[108] = 0; // obj_Wall_Boss_Parent
	global.__objectDepths[109] = 0; // obj_Boss_Preset
	global.__objectDepths[110] = -1; // obj_Thought
	global.__objectDepths[111] = 0; // obj_Wall_Watcher
	global.__objectDepths[112] = 0; // obj_Growing_Sorrows
	global.__objectDepths[113] = 0; // obj_Thought_Cloud
	global.__objectDepths[114] = 0; // obj_amorphous_jello
	global.__objectDepths[115] = 0; // obj_Hand_of_the_Accuser
	global.__objectDepths[116] = 0; // obj_Cursed_Clapper
	global.__objectDepths[117] = 0; // obj_Spooked_Spirit
	global.__objectDepths[118] = 0; // obj_Fire_Starter
	global.__objectDepths[119] = 0; // obj_Horror_Stack
	global.__objectDepths[120] = 0; // obj_Flying_Stacklet
	global.__objectDepths[121] = 0; // obj_Crawling_Stacklet
	global.__objectDepths[122] = 0; // obj_Puck_Man
	global.__objectDepths[123] = 0; // obj_Ninja_Spirit
	global.__objectDepths[124] = 0; // obj_Applause
	global.__objectDepths[125] = 0; // obj_Trash_Terrestrial
	global.__objectDepths[126] = 0; // obj_Spirit_of_Mischief
	global.__objectDepths[127] = 0; // obj_Tri_Ghoul
	global.__objectDepths[128] = 0; // obj_Manifest_Core
	global.__objectDepths[129] = 0; // obj_Manifest_Core_Solid
	global.__objectDepths[130] = 0; // obj_Manifest_Orbital
	global.__objectDepths[131] = 0; // obj_Peering_Spectre
	global.__objectDepths[132] = 0; // obj_Flash_Knight
	global.__objectDepths[133] = 0; // obj_Mine_Watcher
	global.__objectDepths[134] = 0; // obj_Infatuation_Cloud
	global.__objectDepths[135] = 0; // obj_Agony_Amorphous
	global.__objectDepths[136] = 0; // obj_Heart_Ache
	global.__objectDepths[137] = 0; // obj_Puck_Mass
	global.__objectDepths[138] = 0; // obj_Twister_Devil
	global.__objectDepths[139] = 0; // obj_Manic_Wall_Mage
	global.__objectDepths[140] = 0; // obj_Crazy_Eye
	global.__objectDepths[141] = 0; // obj_Animated_Head
	global.__objectDepths[142] = 0; // obj_Sandman
	global.__objectDepths[143] = 0; // obj_Sandman_Thought
	global.__objectDepths[144] = 0; // obj_Sleeper
	global.__objectDepths[145] = -1; // obj_Manifestation
	global.__objectDepths[146] = 0; // obj_Wall_Manifestation
	global.__objectDepths[147] = 0; // obj_Storm_Cloud
	global.__objectDepths[148] = 0; // obj_Soaring_Sorrows
	global.__objectDepths[149] = 0; // obj_Wicked_Spectre
	global.__objectDepths[150] = 0; // obj_Guardian_of_Knowing
	global.__objectDepths[151] = 0; // obj_Chaotic_Unrest
	global.__objectDepths[152] = 0; // obj_Blind_Hunger
	global.__objectDepths[153] = 0; // obj_Amorphous_Prime
	global.__objectDepths[154] = 0; // obj_Masked_Hope_Spirit
	global.__objectDepths[155] = 0; // obj_Masked_Bliss_Spirit
	global.__objectDepths[156] = 0; // obj_Masked_Vanity_Spirit
	global.__objectDepths[157] = 0; // obj_Masked_Loathing_Spirit
	global.__objectDepths[158] = 0; // obj_Masked_Paranoia_Spirit
	global.__objectDepths[159] = 0; // obj_Masked_Despair_Spirit
	global.__objectDepths[160] = 0; // obj_Soul_Hurt
	global.__objectDepths[161] = 0; // obj_Bullet_Parent
	global.__objectDepths[162] = 0; // obj_Basic_Enemy_Bullet_Parent
	global.__objectDepths[163] = 0; // obj_Bounce_Bullet_Parent
	global.__objectDepths[164] = 0; // obj_Fasing_Bullet_Parent
	global.__objectDepths[165] = 0; // obj_Beam_Parent
	global.__objectDepths[166] = 0; // obj_After_Image_Shot
	global.__objectDepths[167] = 0; // obj_Basic_Red_Bullet
	global.__objectDepths[168] = 0; // obj_Basic_Bullet
	global.__objectDepths[169] = 0; // obj_Fake_Bullet
	global.__objectDepths[170] = 0; // obj_Homing_Bullet
	global.__objectDepths[171] = 0; // obj_Slight_Home_Bullet
	global.__objectDepths[172] = 0; // obj_Slight_Home_No_Dir_Bullet
	global.__objectDepths[173] = 0; // obj_Phase_Bullet
	global.__objectDepths[174] = 0; // obj_Direction_Phase_Bullet
	global.__objectDepths[175] = 0; // obj_Speed_UpDown_Bullet
	global.__objectDepths[176] = 0; // obj_Soul_Phase_Bullet
	global.__objectDepths[177] = 0; // obj_Phase_All_Bullet
	global.__objectDepths[178] = 0; // obj_Explode_Hit
	global.__objectDepths[179] = 0; // obj_Phase_All_Direction_Bullet
	global.__objectDepths[180] = 0; // obj_Dimensional_Bullet
	global.__objectDepths[181] = 0; // obj_Dimensional_Direction_Bullet
	global.__objectDepths[182] = 0; // obj_Lob_Bullet
	global.__objectDepths[183] = 0; // obj_Bounce_Bullet
	global.__objectDepths[184] = 0; // obj_Orbital_Bullet
	global.__objectDepths[185] = 0; // obj_Orbit_Bullet
	global.__objectDepths[186] = 0; // obj_Bounce_Direction_Bullet
	global.__objectDepths[187] = 0; // obj_Sporadic_Bullet
	global.__objectDepths[188] = 0; // obj_Direction_Bullet
	global.__objectDepths[189] = 0; // obj_Speed_Up_Direction_Bullet
	global.__objectDepths[190] = 0; // obj_Spin_Bullet
	global.__objectDepths[191] = 0; // obj_Spin_Phase_Bullet
	global.__objectDepths[192] = 0; // obj_Spin_Quick_Phase_Bullet
	global.__objectDepths[193] = 8; // obj_Poison_Pool
	global.__objectDepths[194] = 0; // obj_Fire_Trail
	global.__objectDepths[195] = -1; // obj_Flash_Knight_Sword
	global.__objectDepths[196] = -1; // obj_Flash_Knight_Sword_Minus
	global.__objectDepths[197] = -1; // obj_Flash_Cannon_Arm
	global.__objectDepths[198] = 0; // obj_Flash_Ball
	global.__objectDepths[199] = 0; // obj_Flash_Crystal_Shot
	global.__objectDepths[200] = -1; // obj_Sand_Ball_Barrage
	global.__objectDepths[201] = -1; // obj_Sand_Ball_Punch
	global.__objectDepths[202] = -1; // obj_Sandman_Punch
	global.__objectDepths[203] = 0; // obj_Sandmans_Sword
	global.__objectDepths[204] = 0; // obj_Chaotic_Explode_Shot
	global.__objectDepths[205] = 0; // obj_Demon_Spiral_Shot
	global.__objectDepths[206] = 0; // obj_Wrath_Explode_Shot
	global.__objectDepths[207] = 0; // obj_Fire_Exploder
	global.__objectDepths[208] = 0; // obj_Loathing_Explode_Bullet
	global.__objectDepths[209] = 0; // obj_Exploding_Shot
	global.__objectDepths[210] = 0; // obj_Fright_Bullet
	global.__objectDepths[211] = 0; // obj_Nightmare_Bullet
	global.__objectDepths[212] = 0; // obj_Splash_Bullet
	global.__objectDepths[213] = 0; // obj_Thunder_Bullet
	global.__objectDepths[214] = 0; // obj_Dark_Splash
	global.__objectDepths[215] = 0; // obj_Big_Lightning_Ball
	global.__objectDepths[216] = 0; // obj_Paranoia_Shotgun_Bullet
	global.__objectDepths[217] = 0; // obj_Fire_Spawning_Bullet
	global.__objectDepths[218] = 0; // obj_Jelly_Ball_Bullet
	global.__objectDepths[219] = 0; // obj_Multi_Jelly_Bullet
	global.__objectDepths[220] = 0; // obj_Multi_Poison_Bullet
	global.__objectDepths[221] = 0; // obj_Poison_Ball_Bullet
	global.__objectDepths[222] = 0; // obj_Double_Jelly_Ball_Bullet
	global.__objectDepths[223] = 0; // obj_Wall_Spawning_Bullet
	global.__objectDepths[224] = 0; // obj_Exploding_Fire
	global.__objectDepths[225] = 0; // obj_Vortex_Tornado
	global.__objectDepths[226] = 0; // obj_Chaotic_Flame_Pillar
	global.__objectDepths[227] = 0; // obj_Demon_Flame_Pillar
	global.__objectDepths[228] = 0; // obj_Wandering_Bullet
	global.__objectDepths[229] = 0; // obj_Maelstrom_Bullet
	global.__objectDepths[230] = 0; // obj_Despair_Bullet
	global.__objectDepths[231] = 0; // obj_Despair_Shadow_Bullet
	global.__objectDepths[232] = 0; // obj_Tri_Ghoul_Hand
	global.__objectDepths[233] = 0; // obj_Chaos_Tornado
	global.__objectDepths[234] = 0; // obj_Miner_Bullet
	global.__objectDepths[235] = 0; // obj_Angry_Miner_Bullet
	global.__objectDepths[236] = 0; // obj_Paranoia_Mine_Bullet
	global.__objectDepths[237] = 0; // obj_Homing_Miner
	global.__objectDepths[238] = 0; // obj_Split_Mine_Bullet
	global.__objectDepths[239] = 0; // obj_Drill_Shot
	global.__objectDepths[240] = 0; // obj_Big_Green_Ball
	global.__objectDepths[241] = 0; // obj_Despair_Harpoon
	global.__objectDepths[242] = 0; // obj_Despair_Ball
	global.__objectDepths[243] = 0; // obj_Dimensional_Bliss_Shot
	global.__objectDepths[244] = 0; // obj_Bounce_Bliss_Shot
	global.__objectDepths[245] = 0; // obj_Orbit_Bliss_Shot
	global.__objectDepths[246] = 0; // obj_Rising_Bliss_Shot
	global.__objectDepths[247] = 0; // obj_Come_Back_Bullet
	global.__objectDepths[248] = 0; // obj_Homing_Block_Bullet
	global.__objectDepths[249] = 0; // obj_Extinguishing_Magic
	global.__objectDepths[250] = 0; // obj_Spectre_Big_Blast
	global.__objectDepths[251] = 0; // obj_Wall_Spit_Bullet
	global.__objectDepths[252] = 0; // obj_Exploding_Hope_Bullet
	global.__objectDepths[253] = 0; // obj_Mega_Hope_Ball
	global.__objectDepths[254] = 0; // obj_Chaos_Wave_Shot
	global.__objectDepths[255] = 0; // obj_Double_Bounce_Shot
	global.__objectDepths[256] = 0; // obj_Dormant_Bullet
	global.__objectDepths[257] = 0; // obj_Homing_Dormant_Bullet
	global.__objectDepths[258] = 0; // obj_Hatred_Seeking_Bullet
	global.__objectDepths[259] = 0; // obj_Phasing_Hatred_Bullet
	global.__objectDepths[260] = 0; // obj_Pestilence_Bullet
	global.__objectDepths[261] = 0; // obj_Mischief_Bullet
	global.__objectDepths[262] = 0; // obj_Knowledge_Ball
	global.__objectDepths[263] = 0; // obj_Homing_Mischief
	global.__objectDepths[264] = 0; // obj_Vanity_Soul_Shoot_Bullet
	global.__objectDepths[265] = 0; // obj_Vanity_Shoot_Everywhere_Bullet
	global.__objectDepths[266] = 0; // obj_Distorter_Bullet
	global.__objectDepths[267] = 0; // obj_Sticky_Slide_Bullet
	global.__objectDepths[268] = 0; // obj_Paranoia_Bullet
	global.__objectDepths[269] = 0; // obj_Cross_Split_Bullet
	global.__objectDepths[270] = 0; // obj_Basic_Laser_Bullet
	global.__objectDepths[271] = 0; // obj_Fasing_Laser
	global.__objectDepths[272] = 0; // obj_Gravity_Fasing_Laser
	global.__objectDepths[273] = 0; // obj_Kylie_Bullet
	global.__objectDepths[274] = -1; // obj_Laser_Beam_Charge
	global.__objectDepths[275] = -1; // obj_Laser_Beam
	global.__objectDepths[276] = 0; // obj_Rain_Drop_Bullet
	global.__objectDepths[277] = 1; // obj_Infatuation_Drop_Bullet
	global.__objectDepths[278] = 0; // obj_Attraction_Bullet
	global.__objectDepths[279] = 0; // obj_Phase_Rain
	global.__objectDepths[280] = 0; // obj_Sorrow_Bullet
	global.__objectDepths[281] = 0; // obj_Toxic_Sorrow_Bullet
	global.__objectDepths[282] = 0; // obj_Echolocation_Shot
	global.__objectDepths[283] = 0; // obj_Arcane_Echo
	global.__objectDepths[284] = -2; // obj_Item_Parent
	global.__objectDepths[285] = 0; // obj_Item_Field
	global.__objectDepths[286] = -3; // obj_Recollection_Cloud
	global.__objectDepths[287] = 0; // obj_Item_Spark
	global.__objectDepths[288] = 0; // obj_Gem_Parent
	global.__objectDepths[289] = 0; // obj_Red_Dream_Gem
	global.__objectDepths[290] = 0; // obj_Yellow_Dream_Gem
	global.__objectDepths[291] = 0; // obj_Cyan_Dream_Gem
	global.__objectDepths[292] = 0; // obj_Blue_Dream_Gem
	global.__objectDepths[293] = 0; // obj_Lime_Dream_Gem
	global.__objectDepths[294] = 0; // obj_Pink_Dream_Gem
	global.__objectDepths[295] = 0; // obj_Weapon_Effect
	global.__objectDepths[296] = 0; // obj_Life_Suck
	global.__objectDepths[297] = 0; // obj_Bullet_Conquest
	global.__objectDepths[298] = 0; // obj_Time_Warp
	global.__objectDepths[299] = 0; // obj_Figment_Parent
	global.__objectDepths[300] = 0; // obj_Soul_Minion_Parent
	global.__objectDepths[301] = 0; // obj_Wandering_Soul
	global.__objectDepths[302] = -1; // obj_Fleeting_Soul
	global.__objectDepths[303] = 0; // obj_Fighter_Soul
	global.__objectDepths[304] = 0; // obj_Blaze_Soul
	global.__objectDepths[305] = 0; // obj_Fuse_Soul
	global.__objectDepths[306] = 0; // obj_Spike_Soul
	global.__objectDepths[307] = 0; // obj_Knife_Soul
	global.__objectDepths[308] = 0; // obj_Copy_Cat_Soul
	global.__objectDepths[309] = 0; // obj_Poisonous_Soul
	global.__objectDepths[310] = 0; // obj_Magican_Soul
	global.__objectDepths[311] = 0; // obj_Bleeding_Soul
	global.__objectDepths[312] = 0; // obj_Electro_Soul
	global.__objectDepths[313] = 0; // obj_Clingy_Soul
	global.__objectDepths[314] = 0; // obj_Barrier_Soul
	global.__objectDepths[315] = 0; // obj_Weakening_Soul
	global.__objectDepths[316] = 0; // obj_Friendly_Figment
	global.__objectDepths[317] = 0; // obj_Manifested_Fig
	global.__objectDepths[318] = 0; // obj_Dummy_Figment
	global.__objectDepths[319] = 0; // obj_Shield_Friend
	global.__objectDepths[320] = 0; // obj_Flash_Cannon
	global.__objectDepths[321] = 0; // obj_Healthy_Thoughts
	global.__objectDepths[322] = 0; // obj_Healthy_Essence
	global.__objectDepths[323] = 0; // obj_Corporeal_Chum
	global.__objectDepths[324] = 0; // obj_Glum_Chum
	global.__objectDepths[325] = 0; // obj_Troubling_Thingo
	global.__objectDepths[326] = 0; // obj_Explosive_Manifesto
	global.__objectDepths[327] = 0; // obj_Essential_Thoughts
	global.__objectDepths[328] = 0; // obj_Essential_Essence
	global.__objectDepths[329] = 0; // obj_Bullet_Eater
	global.__objectDepths[330] = 0; // obj_Sore_Eye
	global.__objectDepths[331] = 0; // obj_Warding_Figment
	global.__objectDepths[332] = 0; // obj_Positive_Thoughts
	global.__objectDepths[333] = 0; // obj_Positive_Essence
	global.__objectDepths[334] = 0; // obj_Title_Screen_Effect_Control
	global.__objectDepths[335] = 0; // obj_Menu_Fade_In
	global.__objectDepths[336] = 0; // obj_Start_Button
	global.__objectDepths[337] = -1; // obj_Start_Run_Menu
	global.__objectDepths[338] = -2; // obj_Start_Run_Button
	global.__objectDepths[339] = 0; // obj_Settings_Button
	global.__objectDepths[340] = -1; // obj_Title_Settings_Menu
	global.__objectDepths[341] = 0; // obj_Credits_Button
	global.__objectDepths[342] = 0; // obj_Quit_Button
	global.__objectDepths[343] = -1; // obj_Credits_Menu


	global.__objectNames[0] = "Pause_Control";
	global.__objectNames[1] = "obj_Pause_Parent";
	global.__objectNames[2] = "obj_Soul_Menu_Butt";
	global.__objectNames[3] = "obj_Recollection_Menu_Butt";
	global.__objectNames[4] = "obj_Settings_Menu_Butt";
	global.__objectNames[5] = "obj_Save_Quit";
	global.__objectNames[6] = "obj_Pause";
	global.__objectNames[7] = "obj_Pause_Sparkle";
	global.__objectNames[8] = "obj_Settings_Menu";
	global.__objectNames[9] = "obj_Specific_Setting_Butt";
	global.__objectNames[10] = "obj_Option_Button";
	global.__objectNames[11] = "obj_Option_Pointer";
	global.__objectNames[12] = "obj_Option_Slider";
	global.__objectNames[13] = "obj_Soul_Menu";
	global.__objectNames[14] = "obj_Soul_Stat_Meter";
	global.__objectNames[15] = "obj_Soul_Stat_Calc_Icon";
	global.__objectNames[16] = "obj_Item_Butt";
	global.__objectNames[17] = "obj_Recollection_Menu";
	global.__objectNames[18] = "obj_Recollection_Category_Butt";
	global.__objectNames[19] = "obj_Recollection_Butt";
	global.__objectNames[20] = "obj_Recollect_Spark";
	global.__objectNames[21] = "obj_Recollection_Info_Butt";
	global.__objectNames[22] = "Soul_Hearts_Control";
	global.__objectNames[23] = "obj_Heart_Butt";
	global.__objectNames[24] = "obj_Mouse_Heart";
	global.__objectNames[25] = "Control_Parent";
	global.__objectNames[26] = "Game_Start_Control";
	global.__objectNames[27] = "Chapter_Change_Control";
	global.__objectNames[28] = "Floor_Layout_Control";
	global.__objectNames[29] = "Soul_Weapons_Control";
	global.__objectNames[30] = "Soul_Stat_Control";
	global.__objectNames[31] = "obj_Loading_Screen";
	global.__objectNames[32] = "obj_Depth";
	global.__objectNames[33] = "obj_Depth_Floor";
	global.__objectNames[34] = "Master_Depth_Draw_Control";
	global.__objectNames[35] = "obj_Environmental_Control";
	global.__objectNames[36] = "Music_Control";
	global.__objectNames[37] = "Tutorial_Control";
	global.__objectNames[38] = "Run_Fade_Control";
	global.__objectNames[39] = "Camera_Control";
	global.__objectNames[40] = "Gui_Control";
	global.__objectNames[41] = "obj_Light_Control";
	global.__objectNames[42] = "Boss_Room_Start_Control";
	global.__objectNames[43] = "Normal_Room_Start_Control";
	global.__objectNames[44] = "Item_Room_Control";
	global.__objectNames[45] = "Shop_Room_Control";
	global.__objectNames[46] = "obj_Sparkle_Emitter";
	global.__objectNames[47] = "obj_Heart_Emitter";
	global.__objectNames[48] = "obj_Dream_Emitter";
	global.__objectNames[49] = "obj_Environment_Emitter";
	global.__objectNames[50] = "obj_Damage_Indicator";
	global.__objectNames[51] = "obj_Field_Element";
	global.__objectNames[52] = "obj_Fade";
	global.__objectNames[53] = "obj_Light";
	global.__objectNames[54] = "obj_Border_Impact";
	global.__objectNames[55] = "obj_The_Border";
	global.__objectNames[56] = "obj_Bigger_Border";
	global.__objectNames[57] = "obj_Flash_Sparkle";
	global.__objectNames[58] = "obj_Feel_Heart";
	global.__objectNames[59] = "obj_Dream_Cloud";
	global.__objectNames[60] = "obj_Big_Dream_Cloud";
	global.__objectNames[61] = "obj_Medium_Room_Wall";
	global.__objectNames[62] = "obj_Astral_Indicator";
	global.__objectNames[63] = "obj_Charge_Indicator";
	global.__objectNames[64] = "obj_Dream_Cursor";
	global.__objectNames[65] = "obj_Soul";
	global.__objectNames[66] = "obj_Soul_Parent";
	global.__objectNames[67] = "obj_Soul_Flash";
	global.__objectNames[68] = "obj_Soul_Spiritual";
	global.__objectNames[69] = "obj_Soul_Feel";
	global.__objectNames[70] = "obj_Soul_Dream";
	global.__objectNames[71] = "obj_Soul_Bit";
	global.__objectNames[72] = "obj_Broken_Heart";
	global.__objectNames[73] = "obj_Soul_Linger";
	global.__objectNames[74] = "obj_Dream_Glitch";
	global.__objectNames[75] = "obj_Soul_Nightmare";
	global.__objectNames[76] = "obj_Basic_Soul";
	global.__objectNames[77] = "obj_Projectile_Parent";
	global.__objectNames[78] = "obj_Basic_Projectile_Parent";
	global.__objectNames[79] = "obj_Lesser_Soul_Shot";
	global.__objectNames[80] = "obj_Defense_Soul_Shot";
	global.__objectNames[81] = "obj_Essence_Impact_Show";
	global.__objectNames[82] = "obj_Direction_Soul_Shot";
	global.__objectNames[83] = "obj_Minion_Parent";
	global.__objectNames[84] = "obj_Minion_Phase";
	global.__objectNames[85] = "obj_Spooked_Ghoul";
	global.__objectNames[86] = "obj_Wall_Fiend";
	global.__objectNames[87] = "obj_Re_Animated";
	global.__objectNames[88] = "obj_Mini_Manifest";
	global.__objectNames[89] = "obj_Unrest_Spirit";
	global.__objectNames[90] = "obj_Wrath_Spirit";
	global.__objectNames[91] = "obj_Demon_Unrest";
	global.__objectNames[92] = "obj_Distorted_Ghoul";
	global.__objectNames[93] = "obj_Hope_Mask";
	global.__objectNames[94] = "obj_Jello_Minion";
	global.__objectNames[95] = "obj_Jumpy_Slime";
	global.__objectNames[96] = "obj_Scary_Heart";
	global.__objectNames[97] = "obj_Hand_Slime";
	global.__objectNames[98] = "obj_Toxic_Slime";
	global.__objectNames[99] = "obj_Spike_Slime";
	global.__objectNames[100] = "obj_Poison_Jello";
	global.__objectNames[101] = "obj_Jello_Cube";
	global.__objectNames[102] = "obj_Poison_Cube";
	global.__objectNames[103] = "obj_Boss_Parent";
	global.__objectNames[104] = "obj_Main_Boss_Parent";
	global.__objectNames[105] = "obj_Non_Solid_Boss_Parent";
	global.__objectNames[106] = "obj_Wall_Stop_Boss_Parent";
	global.__objectNames[107] = "obj_Boost_Spark";
	global.__objectNames[108] = "obj_Wall_Boss_Parent";
	global.__objectNames[109] = "obj_Boss_Preset";
	global.__objectNames[110] = "obj_Thought";
	global.__objectNames[111] = "obj_Wall_Watcher";
	global.__objectNames[112] = "obj_Growing_Sorrows";
	global.__objectNames[113] = "obj_Thought_Cloud";
	global.__objectNames[114] = "obj_amorphous_jello";
	global.__objectNames[115] = "obj_Hand_of_the_Accuser";
	global.__objectNames[116] = "obj_Cursed_Clapper";
	global.__objectNames[117] = "obj_Spooked_Spirit";
	global.__objectNames[118] = "obj_Fire_Starter";
	global.__objectNames[119] = "obj_Horror_Stack";
	global.__objectNames[120] = "obj_Flying_Stacklet";
	global.__objectNames[121] = "obj_Crawling_Stacklet";
	global.__objectNames[122] = "obj_Puck_Man";
	global.__objectNames[123] = "obj_Ninja_Spirit";
	global.__objectNames[124] = "obj_Applause";
	global.__objectNames[125] = "obj_Trash_Terrestrial";
	global.__objectNames[126] = "obj_Spirit_of_Mischief";
	global.__objectNames[127] = "obj_Tri_Ghoul";
	global.__objectNames[128] = "obj_Manifest_Core";
	global.__objectNames[129] = "obj_Manifest_Core_Solid";
	global.__objectNames[130] = "obj_Manifest_Orbital";
	global.__objectNames[131] = "obj_Peering_Spectre";
	global.__objectNames[132] = "obj_Flash_Knight";
	global.__objectNames[133] = "obj_Mine_Watcher";
	global.__objectNames[134] = "obj_Infatuation_Cloud";
	global.__objectNames[135] = "obj_Agony_Amorphous";
	global.__objectNames[136] = "obj_Heart_Ache";
	global.__objectNames[137] = "obj_Puck_Mass";
	global.__objectNames[138] = "obj_Twister_Devil";
	global.__objectNames[139] = "obj_Manic_Wall_Mage";
	global.__objectNames[140] = "obj_Crazy_Eye";
	global.__objectNames[141] = "obj_Animated_Head";
	global.__objectNames[142] = "obj_Sandman";
	global.__objectNames[143] = "obj_Sandman_Thought";
	global.__objectNames[144] = "obj_Sleeper";
	global.__objectNames[145] = "obj_Manifestation";
	global.__objectNames[146] = "obj_Wall_Manifestation";
	global.__objectNames[147] = "obj_Storm_Cloud";
	global.__objectNames[148] = "obj_Soaring_Sorrows";
	global.__objectNames[149] = "obj_Wicked_Spectre";
	global.__objectNames[150] = "obj_Guardian_of_Knowing";
	global.__objectNames[151] = "obj_Chaotic_Unrest";
	global.__objectNames[152] = "obj_Blind_Hunger";
	global.__objectNames[153] = "obj_Amorphous_Prime";
	global.__objectNames[154] = "obj_Masked_Hope_Spirit";
	global.__objectNames[155] = "obj_Masked_Bliss_Spirit";
	global.__objectNames[156] = "obj_Masked_Vanity_Spirit";
	global.__objectNames[157] = "obj_Masked_Loathing_Spirit";
	global.__objectNames[158] = "obj_Masked_Paranoia_Spirit";
	global.__objectNames[159] = "obj_Masked_Despair_Spirit";
	global.__objectNames[160] = "obj_Soul_Hurt";
	global.__objectNames[161] = "obj_Bullet_Parent";
	global.__objectNames[162] = "obj_Basic_Enemy_Bullet_Parent";
	global.__objectNames[163] = "obj_Bounce_Bullet_Parent";
	global.__objectNames[164] = "obj_Fasing_Bullet_Parent";
	global.__objectNames[165] = "obj_Beam_Parent";
	global.__objectNames[166] = "obj_After_Image_Shot";
	global.__objectNames[167] = "obj_Basic_Red_Bullet";
	global.__objectNames[168] = "obj_Basic_Bullet";
	global.__objectNames[169] = "obj_Fake_Bullet";
	global.__objectNames[170] = "obj_Homing_Bullet";
	global.__objectNames[171] = "obj_Slight_Home_Bullet";
	global.__objectNames[172] = "obj_Slight_Home_No_Dir_Bullet";
	global.__objectNames[173] = "obj_Phase_Bullet";
	global.__objectNames[174] = "obj_Direction_Phase_Bullet";
	global.__objectNames[175] = "obj_Speed_UpDown_Bullet";
	global.__objectNames[176] = "obj_Soul_Phase_Bullet";
	global.__objectNames[177] = "obj_Phase_All_Bullet";
	global.__objectNames[178] = "obj_Explode_Hit";
	global.__objectNames[179] = "obj_Phase_All_Direction_Bullet";
	global.__objectNames[180] = "obj_Dimensional_Bullet";
	global.__objectNames[181] = "obj_Dimensional_Direction_Bullet";
	global.__objectNames[182] = "obj_Lob_Bullet";
	global.__objectNames[183] = "obj_Bounce_Bullet";
	global.__objectNames[184] = "obj_Orbital_Bullet";
	global.__objectNames[185] = "obj_Orbit_Bullet";
	global.__objectNames[186] = "obj_Bounce_Direction_Bullet";
	global.__objectNames[187] = "obj_Sporadic_Bullet";
	global.__objectNames[188] = "obj_Direction_Bullet";
	global.__objectNames[189] = "obj_Speed_Up_Direction_Bullet";
	global.__objectNames[190] = "obj_Spin_Bullet";
	global.__objectNames[191] = "obj_Spin_Phase_Bullet";
	global.__objectNames[192] = "obj_Spin_Quick_Phase_Bullet";
	global.__objectNames[193] = "obj_Poison_Pool";
	global.__objectNames[194] = "obj_Fire_Trail";
	global.__objectNames[195] = "obj_Flash_Knight_Sword";
	global.__objectNames[196] = "obj_Flash_Knight_Sword_Minus";
	global.__objectNames[197] = "obj_Flash_Cannon_Arm";
	global.__objectNames[198] = "obj_Flash_Ball";
	global.__objectNames[199] = "obj_Flash_Crystal_Shot";
	global.__objectNames[200] = "obj_Sand_Ball_Barrage";
	global.__objectNames[201] = "obj_Sand_Ball_Punch";
	global.__objectNames[202] = "obj_Sandman_Punch";
	global.__objectNames[203] = "obj_Sandmans_Sword";
	global.__objectNames[204] = "obj_Chaotic_Explode_Shot";
	global.__objectNames[205] = "obj_Demon_Spiral_Shot";
	global.__objectNames[206] = "obj_Wrath_Explode_Shot";
	global.__objectNames[207] = "obj_Fire_Exploder";
	global.__objectNames[208] = "obj_Loathing_Explode_Bullet";
	global.__objectNames[209] = "obj_Exploding_Shot";
	global.__objectNames[210] = "obj_Fright_Bullet";
	global.__objectNames[211] = "obj_Nightmare_Bullet";
	global.__objectNames[212] = "obj_Splash_Bullet";
	global.__objectNames[213] = "obj_Thunder_Bullet";
	global.__objectNames[214] = "obj_Dark_Splash";
	global.__objectNames[215] = "obj_Big_Lightning_Ball";
	global.__objectNames[216] = "obj_Paranoia_Shotgun_Bullet";
	global.__objectNames[217] = "obj_Fire_Spawning_Bullet";
	global.__objectNames[218] = "obj_Jelly_Ball_Bullet";
	global.__objectNames[219] = "obj_Multi_Jelly_Bullet";
	global.__objectNames[220] = "obj_Multi_Poison_Bullet";
	global.__objectNames[221] = "obj_Poison_Ball_Bullet";
	global.__objectNames[222] = "obj_Double_Jelly_Ball_Bullet";
	global.__objectNames[223] = "obj_Wall_Spawning_Bullet";
	global.__objectNames[224] = "obj_Exploding_Fire";
	global.__objectNames[225] = "obj_Vortex_Tornado";
	global.__objectNames[226] = "obj_Chaotic_Flame_Pillar";
	global.__objectNames[227] = "obj_Demon_Flame_Pillar";
	global.__objectNames[228] = "obj_Wandering_Bullet";
	global.__objectNames[229] = "obj_Maelstrom_Bullet";
	global.__objectNames[230] = "obj_Despair_Bullet";
	global.__objectNames[231] = "obj_Despair_Shadow_Bullet";
	global.__objectNames[232] = "obj_Tri_Ghoul_Hand";
	global.__objectNames[233] = "obj_Chaos_Tornado";
	global.__objectNames[234] = "obj_Miner_Bullet";
	global.__objectNames[235] = "obj_Angry_Miner_Bullet";
	global.__objectNames[236] = "obj_Paranoia_Mine_Bullet";
	global.__objectNames[237] = "obj_Homing_Miner";
	global.__objectNames[238] = "obj_Split_Mine_Bullet";
	global.__objectNames[239] = "obj_Drill_Shot";
	global.__objectNames[240] = "obj_Big_Green_Ball";
	global.__objectNames[241] = "obj_Despair_Harpoon";
	global.__objectNames[242] = "obj_Despair_Ball";
	global.__objectNames[243] = "obj_Dimensional_Bliss_Shot";
	global.__objectNames[244] = "obj_Bounce_Bliss_Shot";
	global.__objectNames[245] = "obj_Orbit_Bliss_Shot";
	global.__objectNames[246] = "obj_Rising_Bliss_Shot";
	global.__objectNames[247] = "obj_Come_Back_Bullet";
	global.__objectNames[248] = "obj_Homing_Block_Bullet";
	global.__objectNames[249] = "obj_Extinguishing_Magic";
	global.__objectNames[250] = "obj_Spectre_Big_Blast";
	global.__objectNames[251] = "obj_Wall_Spit_Bullet";
	global.__objectNames[252] = "obj_Exploding_Hope_Bullet";
	global.__objectNames[253] = "obj_Mega_Hope_Ball";
	global.__objectNames[254] = "obj_Chaos_Wave_Shot";
	global.__objectNames[255] = "obj_Double_Bounce_Shot";
	global.__objectNames[256] = "obj_Dormant_Bullet";
	global.__objectNames[257] = "obj_Homing_Dormant_Bullet";
	global.__objectNames[258] = "obj_Hatred_Seeking_Bullet";
	global.__objectNames[259] = "obj_Phasing_Hatred_Bullet";
	global.__objectNames[260] = "obj_Pestilence_Bullet";
	global.__objectNames[261] = "obj_Mischief_Bullet";
	global.__objectNames[262] = "obj_Knowledge_Ball";
	global.__objectNames[263] = "obj_Homing_Mischief";
	global.__objectNames[264] = "obj_Vanity_Soul_Shoot_Bullet";
	global.__objectNames[265] = "obj_Vanity_Shoot_Everywhere_Bullet";
	global.__objectNames[266] = "obj_Distorter_Bullet";
	global.__objectNames[267] = "obj_Sticky_Slide_Bullet";
	global.__objectNames[268] = "obj_Paranoia_Bullet";
	global.__objectNames[269] = "obj_Cross_Split_Bullet";
	global.__objectNames[270] = "obj_Basic_Laser_Bullet";
	global.__objectNames[271] = "obj_Fasing_Laser";
	global.__objectNames[272] = "obj_Gravity_Fasing_Laser";
	global.__objectNames[273] = "obj_Kylie_Bullet";
	global.__objectNames[274] = "obj_Laser_Beam_Charge";
	global.__objectNames[275] = "obj_Laser_Beam";
	global.__objectNames[276] = "obj_Rain_Drop_Bullet";
	global.__objectNames[277] = "obj_Infatuation_Drop_Bullet";
	global.__objectNames[278] = "obj_Attraction_Bullet";
	global.__objectNames[279] = "obj_Phase_Rain";
	global.__objectNames[280] = "obj_Sorrow_Bullet";
	global.__objectNames[281] = "obj_Toxic_Sorrow_Bullet";
	global.__objectNames[282] = "obj_Echolocation_Shot";
	global.__objectNames[283] = "obj_Arcane_Echo";
	global.__objectNames[284] = "obj_Item_Parent";
	global.__objectNames[285] = "obj_Item_Field";
	global.__objectNames[286] = "obj_Recollection_Cloud";
	global.__objectNames[287] = "obj_Item_Spark";
	global.__objectNames[288] = "obj_Gem_Parent";
	global.__objectNames[289] = "obj_Red_Dream_Gem";
	global.__objectNames[290] = "obj_Yellow_Dream_Gem";
	global.__objectNames[291] = "obj_Cyan_Dream_Gem";
	global.__objectNames[292] = "obj_Blue_Dream_Gem";
	global.__objectNames[293] = "obj_Lime_Dream_Gem";
	global.__objectNames[294] = "obj_Pink_Dream_Gem";
	global.__objectNames[295] = "obj_Weapon_Effect";
	global.__objectNames[296] = "obj_Life_Suck";
	global.__objectNames[297] = "obj_Bullet_Conquest";
	global.__objectNames[298] = "obj_Time_Warp";
	global.__objectNames[299] = "obj_Figment_Parent";
	global.__objectNames[300] = "obj_Soul_Minion_Parent";
	global.__objectNames[301] = "obj_Wandering_Soul";
	global.__objectNames[302] = "obj_Fleeting_Soul";
	global.__objectNames[303] = "obj_Fighter_Soul";
	global.__objectNames[304] = "obj_Blaze_Soul";
	global.__objectNames[305] = "obj_Fuse_Soul";
	global.__objectNames[306] = "obj_Spike_Soul";
	global.__objectNames[307] = "obj_Knife_Soul";
	global.__objectNames[308] = "obj_Copy_Cat_Soul";
	global.__objectNames[309] = "obj_Poisonous_Soul";
	global.__objectNames[310] = "obj_Magican_Soul";
	global.__objectNames[311] = "obj_Bleeding_Soul";
	global.__objectNames[312] = "obj_Electro_Soul";
	global.__objectNames[313] = "obj_Clingy_Soul";
	global.__objectNames[314] = "obj_Barrier_Soul";
	global.__objectNames[315] = "obj_Weakening_Soul";
	global.__objectNames[316] = "obj_Friendly_Figment";
	global.__objectNames[317] = "obj_Manifested_Fig";
	global.__objectNames[318] = "obj_Dummy_Figment";
	global.__objectNames[319] = "obj_Shield_Friend";
	global.__objectNames[320] = "obj_Flash_Cannon";
	global.__objectNames[321] = "obj_Healthy_Thoughts";
	global.__objectNames[322] = "obj_Healthy_Essence";
	global.__objectNames[323] = "obj_Corporeal_Chum";
	global.__objectNames[324] = "obj_Glum_Chum";
	global.__objectNames[325] = "obj_Troubling_Thingo";
	global.__objectNames[326] = "obj_Explosive_Manifesto";
	global.__objectNames[327] = "obj_Essential_Thoughts";
	global.__objectNames[328] = "obj_Essential_Essence";
	global.__objectNames[329] = "obj_Bullet_Eater";
	global.__objectNames[330] = "obj_Sore_Eye";
	global.__objectNames[331] = "obj_Warding_Figment";
	global.__objectNames[332] = "obj_Positive_Thoughts";
	global.__objectNames[333] = "obj_Positive_Essence";
	global.__objectNames[334] = "obj_Title_Screen_Effect_Control";
	global.__objectNames[335] = "obj_Menu_Fade_In";
	global.__objectNames[336] = "obj_Start_Button";
	global.__objectNames[337] = "obj_Start_Run_Menu";
	global.__objectNames[338] = "obj_Start_Run_Button";
	global.__objectNames[339] = "obj_Settings_Button";
	global.__objectNames[340] = "obj_Title_Settings_Menu";
	global.__objectNames[341] = "obj_Credits_Button";
	global.__objectNames[342] = "obj_Quit_Button";
	global.__objectNames[343] = "obj_Credits_Menu";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
